apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: anzogwebapitry1
  name: anzogwebapitry1
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: anzogwebapitry1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: anzogwebapitry1
    spec:
      containers:
        - image: gcr.io/ag-kixsandbox-6/github.com/arekgoral/anz-test
          imagePullPolicy: IfNotPresent
          name: anz-test-1
